name: Oppgaveseks

on:
  push:
    branches:
      - main

jobs:
  multidulti:

    runs-on: ubuntu-latest

    steps:
      - name: What's the answer to life, the universe and everything?
        id: whats-the-answer
        run: |
          echo "answer=42" >> "$GITHUB_OUTPUT"

      - name: Use the answer
        run: |
          echo "The answer is ${{ steps.whats-the-answer.outputs.answer  }}"

      - name: Find the current time in Oslo
        run: |
          echo "json-response<<EOF" >> $GITHUB_OUTPUT
          curl "http://worldtimeapi.org/api/timezone/Europe/Oslo" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT 
