name: Yo Mama

on:
  - pull_request

jobs:
  yo_mama_job:
    name: Yo Mama
    runs-on: ubuntu-latest

    steps:
      - name: Print message to terminal
        run: echo "Yo Mam"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Builderino
        run: npm run build

  linter_job:
    name: linterino
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Run linter
        run: npm run lint:check

  test_job:
    name: testerino
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Run tests
        run: npm run test

  post_comment_jobb:
    runs-on: ubuntu-latest

    needs: [yo_mama_job, linter_job, test_job]

    steps:
      - name: Post comments
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            All jobs have finished! 🎉
